language: node_js
node_js:
  - node
script:
  - npm run build
deploy:
  provider: npm
  edge: true
  email: $NPM_EMAIL
  api_token: $NPM_TOKEN
  skip_cleanup: true
  script: echo "Deploying to npm ..." && echo $NPM_EMAIl
  on:
    tags: true
    branch: master
