language: node_js

os: linux

node_js:
  - node

script:
  - npm run build

before_deploy:
  - echo $NPM_EMAIl
  - echo "Deploying to npm ..."

deploy:
  provider: npm
  edge: true
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  cleanup: false
  on:
    tags: true
    branch: master
